export { BeckonProvider, useBeckonConfig, useOptionalBeckonConfig } from "./provider"
export { BeckonWidget } from "./widget"
export { BeckonCopilot } from "./copilot"
export { ChatSurface } from "./chat-surface"
export { injectStyles } from "./inject"
export { WIDGET_STYLES } from "./styles"
export type { BeckonConfig, ClientToolSpec } from "@beckon/client"
